# Generated by Django 5.2.8 on 2025-11-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagen de Portada'),
        ),
    ]
