# Generated by Django 6.0.1 on 2026-01-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogInfo", "0004_mensajecontacto_post_likes_post_vistas_notificacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mensajecontacto",
            name="email",
        ),
        migrations.AddField(
            model_name="mensajecontacto",
            name="telefono",
            field=models.CharField(default=1, max_length=15, verbose_name="Teléfono"),
            preserve_default=False,
        ),
    ]
