# Generated by Django 5.2.8 on 2026-01-15 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogInfo", "0005_remove_mensajecontacto_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensajecontacto",
            name="telefono",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono debe tener formato 379XXXXXXX (10 dígitos, Corrientes). Ej: 3794095682",
                        regex="^379\\d{7}$",
                    )
                ],
                verbose_name="Teléfono",
            ),
        ),
    ]
