# Generated by Django 5.2.8 on 2026-01-15 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogInfo", "0006_alter_mensajecontacto_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensajecontacto",
            name="telefono",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono debe tener formato 37XXXXXXXX (10 dígitos, Corrientes). Ej: 3794095682",
                        regex="^37\\d{8}$",
                    )
                ],
                verbose_name="Teléfono",
            ),
        ),
    ]
